{{- if .Values.ingress.enabled -}}
{{- $fullName := include "chart.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $additionalPathsHigherPriority := .Values.ingress.additionalPathsHigherPriority }}
{{- $additionalPaths := .Values.ingress.additionalPaths }}
{{- $servicePort := .Values.ingress.servicePort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  {{- if .Values.ingress.annotations }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
{{- with .Values.ingress.tls }}
  tls:
{{ toYaml . | indent 4}}
{{- end }}
{{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range $additionalPathsHigherPriority }}
          - path: {{ .path }}
            backend:
              serviceName: {{ if .serviceName }}{{ .serviceName }}{{ else }}{{ $fullName }}{{ end }}
              servicePort: {{ .servicePort }}
          {{- end }}
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
          {{- range $additionalPaths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ if .serviceName }}{{ .serviceName }}{{ else }}{{ $fullName }}{{ end }}
              servicePort: {{ .servicePort }}
          {{- end }}
    {{- end }}
    {{- else }}
    - http:
        paths:
          {{- range $additionalPathsHigherPriority }}
          - path: {{ .path }}
            backend:
              serviceName: {{ if .serviceName }}{{ .serviceName }}{{ else }}{{ $fullName }}{{ end }}
              servicePort: {{ .servicePort }}
          {{- end }}
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
          {{- range $additionalPaths }}
          - path: {{ .path }}
            backend:
              serviceName: {{ if .serviceName }}{{ .serviceName }}{{ else }}{{ $fullName }}{{ end }}
              servicePort: {{ .servicePort }}
          {{- end }}

    {{- end }}
{{- end }}